### Login
# @name login
POST https://demo.duendesoftware.com/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=m2m&client_secret=secret&scope=api


### Enqueue an estimation
# @name estimation
@token={{login.response.body.access_token}}

POST https://localhost:5000/Estimations HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "callBackUri": "https://localhost:5004/Notification",
	"imageUrls": [
	  "https://localhost:5001/images/image01.png",
	  "https://localhost:5001/images/image02.jpg"
	]
}

### Get estimation status
# @name status
@case-id={{estimation.response.body.token}}

GET https://localhost:5000/Estimations/{{case-id}} HTTP/1.1
Authorization: Bearer {{token}}